linters:
  enable-all: true
  disable:
    - golint # deprecated
    - interfacer # deprecated
    - maligned # deprecated
    - scopelint # deprecated
    - varnamelen

linters-settings:
  govet:
    enable-all: true
